services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  account:
    build:
      context: ./account
      dockerfile: Dockerfile
    container_name: account
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - client
  account_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: accountdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d accountdb"]
      interval: 5s
      timeout: 3s
      retries: 20

  audit_db:
    image: postgres:15-alpine
    container_name: audit-postgres
    environment:
      POSTGRES_DB: auditdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5434:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auditdb"]
      interval: 5s
      timeout: 3s
      retries: 20
  broker:
    image: redpandadata/redpanda:v24.2.6
    container_name: redpanda
    command: >
      redpanda start
      --overprovisioned
      --smp 1
      --memory 512M
      --reserve-memory 0M
      --node-id 0
      --check=false
      --kafka-addr INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      --advertise-kafka-addr INTERNAL://broker:29092,EXTERNAL://localhost:9092
    ports:
      - "9092:9092"   # externo
      - "29092:29092" # interno
    healthcheck:
      # Desde dentro de la red docker usamos broker:29092
      test: ["CMD-SHELL", "rpk cluster info -X brokers=broker:29092 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  audit:
    build:
      context: ./audit
      dockerfile: Dockerfile
    container_name: audit
    depends_on:
      audit_db:
        condition: service_healthy
      broker:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports: ["8082:8082"]

